version=0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-java-codeguru"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bxzgso2mi830"
s3_prefix = "sam-java-codeguru"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

